version: '3.8'

volumes:
  postgres_data:
  static:
  media:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ports:
      - ${ES_PORT}:${ES_PORT}

  theatre-db:
    image: postgres:13-alpine
    volumes:
      - ./project/simple_project/database_dump.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${SQL_PORT}:${SQL_PORT}

  service:
    build:
      context: ./
      dockerfile: ./project/simple_project/app/Dockerfile
    volumes:
      - static:/opt/app/static
      - media:/opt/app/media
    env_file:
      - .env
    depends_on:
      - theatre-db
