version: '3.8'

volumes:
  postgres_data:
  static:
  media:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - discovery.type=${DISCOVERY_TYPE}
      - bootstrap.memory_lock=${BOOTSTRAP_MEMORY_LOCK}
      - xpack.security.enabled=${XPACK_SECURITY_ENABLED}
      - xpack.security.http.ssl.enabled=${XPACK_SECURITY_HTTP_SSL_ENABLED}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - ${ES_PORT}:${ES_PORT}

  theatre-db:
    image: postgres:13-alpine
    volumes:
      - ./project/simple_project/database_dump.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${SQL_PORT}:${SQL_PORT}
