volumes:
  postgres_data:
  static:
  media:

services:
  service:
    build: app
    volumes:
      - static:/opt/app/static
      - media:/opt/app/media
    env_file:
      - .env
    depends_on:
      - theatre-db

  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static:/var/www/static
      - media:/var/www/media
    env_file:
      - .env
    depends_on:
      - service
      - theatre-db

  theatre-db:
    image: postgres:13-alpine
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ../../django_api/openapi.yaml:/openapi.yaml
    env_file:
      - .env
    depends_on:
      - service
